### String Matching Practice

**(April 11, 2024)**

In [1]:
from tqdm.notebook import tqdm

#### Custom String Matching Score Functions

In [2]:
import string
import numpy as np

### Loading in Data

In [3]:
import pandas as pd

In [5]:
# reading in election data; File is not stored locally in this repository
election_data = pd.read_csv('raw_feb_23_city_wide.csv', dtype=str)

In [6]:
election_data

,Last_Name,First_Name,Middle_Name,Name_Style,Street_Number,Street_Name,Street_Type,Street_Dir_Suffix,Unit_Type,Apartment_Number,...,SPECIAL ELECTION WARD 4 AND 8(Apr/28/2015),DISTRICT OF COLUMBIA GENERAL ELECTI(Nov/04/2014),SPECIAL BD OF ED ELECTION WARD 8(Jul/15/2014),DC MAYORAL PRIMARY 2014(Apr/01/2014),DIST OF COLUMBIA AT-LARGE SPECIAL E(Apr/23/2013),DISTRICT OF COLUMBIA GENERAL ELECTI(Nov/06/2012),SPECIAL ELECTION WARD 5 COUNCIL(May/15/2012),DC PRESIDENTIAL PREF/COUNCIL PRIMAR(Apr/03/2012),RECALL SPECIAL ELECTION 4B04(Feb/28/2012),2011 DISTRICT OF COLUMBIA SPECIAL E(Apr/26/2011)
0,A Blessing,Rebecca,Ann,NaN,1722,19th,ST,NW,APT,706,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A-Jaoudi,Edward,NaN,NaN,2503,Ralph Ellison,Way,NE,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Aaberg,Elizabeth,Margaret,NaN,3019,15th,ST,NW,APT,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Aaby,Erik,NaN,NaN,1300,4th,St,SE,NaN,UNIT 715,...,N,NaN,N,NaN,NaN,N,NaN,NaN,NaN,NaN
4,Aaby,Katherine,Diane,NaN,1854,Park,Rd,NW,NaN,NaN,...,N,NaN,N,N,NaN,A,N,N,N,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
520556,Zytnick,Jonathon,NaN,NaN,425,L,ST,NW,NaN,305,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
520557,Zytnick,Kiva,Keane,NaN,1303,Newton,St,NE,NaN,NaN,...,N,Y,N,Y,NaN,P,N,NaN,N,A
520558,Zywokarte,Michael,Donald,NaN,1265,4th,St,SW,NaN,NaN,...,N,A,N,A,Y,A,N,NaN,N,A
520559,Zywokarte,Sandra,Leigh,NaN,1265,4th,St,SW,NaN,NaN,...,N,A,N,A,Y,A,N,NaN,N,A
520560,Zyznieuski,Nicholas,Michael,NaN,2829,Connecticut,Ave,NW,NaN,712,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# generating list of names
first_name_list = list(election_data['First_Name'])
last_name_list = list(election_data['Last_Name'])
full_name_list = [str(char1) + ' ' + str(char2) for char1, char2 in zip(first_name_list, last_name_list)]

#### Rapid Fuzzy Match

https://rapidfuzz.github.io/RapidFuzz/Usage/fuzz.html#rapidfuzz.fuzz.partial_ratio

In [8]:
from rapidfuzz import fuzz

In [9]:
# https://rapidfuzz.github.io/RapidFuzz/Usage/fuzz.html#rapidfuzz.fuzz.partial_ratio

In [10]:
def score_function_fuzz(guess_full_name, full_name_list):

    full_name_score_dict = dict()
    for idx in tqdm(range(len(full_name_list))):

        # getting full name for row
        name_row = str(full_name_list[idx])

        # lowering strings    
        name_row = name_row.lower()
        guess_full_name = guess_full_name.lower()
    
        # compiling scores
        final_score = fuzz.ratio(guess_full_name, name_row)/100
        full_name_score_dict[idx] = final_score

    # sorting dictionary
    sorted_dictionary = dict(sorted(full_name_score_dict.items(), reverse=True, key=lambda item: item[1]))

    # top five key value pairs (indices and scores)
    indices_scores_list = list(sorted_dictionary.items())[:5]

    return indices_scores_list

#### Finding Similar Data Base Entries

In [12]:
# displaying last and first name only
election_data[['Last_Name', 'First_Name']]

         Last_Name First_Name
0       A Blessing    Rebecca
1         A-Jaoudi     Edward
2           Aaberg  Elizabeth
3             Aaby       Erik
4             Aaby  Katherine
...            ...        ...
520556     Zytnick   Jonathon
520557     Zytnick       Kiva
520558   Zywokarte    Michael
520559   Zywokarte     Sandra
520560  Zyznieuski   Nicholas

[520561 rows x 2 columns]

In [13]:
# finding elmements in election database that are similar to a given string
score_function_fuzz('Alexandra Karabatos', full_name_list)

  0%|          | 0/520561 [00:00<?, ?it/s]

[(247654, 0.9743589743589743),
 (247699, 0.85),
 (407872, 0.8333333333333335),
 (261560, 0.8235294117647058),
 (261711, 0.8235294117647058)]

In [14]:
# Testing the element
election_data.iloc[247654]

Last_Name                                           Karabatsos
First_Name                                           Alexandra
Middle_Name                                              Maria
Name_Style                                                 NaN
Street_Number                                             1300
Street_Name                                                  K
Street_Type                                                 ST
Street_Dir_Suffix                                           SE
Unit_Type                                                  APT
Apartment_Number                                           302
City_Name                                           Washington
Zip_Code                                                 20003
Registration_Date                                   2021-10-16
Party                                                      DEM
Precinct                                                 91.04
SMD                                                       6B09
ANC                                                         6B
WARD                                                       6.0
Voter Status                                               ACT
2022 GENERAL ELECTION(Nov/08/2022)                           A
2022 PRIMARY ELECTION(Jun/21/2022)                           A
2020 DC PRESIDENTIAL GENERAL ELECTI(Nov/03/2020)           NaN
2020 SPECIAL ELECTION WARD 2(Jun/16/2020)                  NaN
2020 DC PRESIDENTIAL PRIMARY ELECTI(Jun/02/2020)           NaN
2018 SPECIAL WARD 4 BOARD OF ED ELE(Dec/04/2018)           NaN
2018 DC GENERAL ELECTION(Nov/06/2018)                      NaN
2018 DC MAYORAL PRIMARY(Jun/19/2018)                       NaN
2016  DC PRESIDENTIALGENERAL ELECTI(Nov/08/2016)           NaN
2016 PRESIDENTIAL PRIMARY ELECTION(Jun/14/2016)            NaN
SPECIAL ELECTION WARD 4 AND 8(Apr/28/2015)                 NaN
DISTRICT OF COLUMBIA GENERAL ELECTI(Nov/04/2014)           NaN
SPECIAL BD OF ED ELECTION WARD 8(Jul/15/2014)              NaN
DC MAYORAL PRIMARY 2014(Apr/01/2014)                       NaN
DIST OF COLUMBIA AT-LARGE SPECIAL E(Apr/23/2013)           NaN
DISTRICT OF COLUMBIA GENERAL ELECTI(Nov/06/2012)           NaN
SPECIAL ELECTION WARD 5 COUNCIL(May/15/2012)               NaN
DC PRESIDENTIAL PREF/COUNCIL PRIMAR(Apr/03/2012)           NaN
RECALL SPECIAL ELECTION 4B04(Feb/28/2012)                  NaN
2011 DISTRICT OF COLUMBIA SPECIAL E(Apr/26/2011)           NaN
Name: 247654, dtype: object